CREATE TABLE `adam`.`dde` (
`subject` VARCHAR( 100 ) NOT NULL DEFAULT '0',
`datestamp` DATE NOT NULL DEFAULT '0000-00-00',
`timestamp` TIME NOT NULL DEFAULT '00:00:00',
`version` VARCHAR( 20 ) NOT NULL DEFAULT '',
`type` INT( 5 ) NOT NULL DEFAULT '0',
`goal` INT( 5 ) NOT NULL DEFAULT '0',
`OptNum` INT( 5 ) NOT NULL DEFAULT '0',
`Action` INT( 5 ) NOT NULL DEFAULT '0',
`S2` INT( 5 ) NOT NULL DEFAULT '0',
`Re` INT( 5 ) NOT NULL DEFAULT '0',
`rt1` VARCHAR( 10 ) NOT NULL DEFAULT '',
`rt2` VARCHAR( 10 ) NOT NULL DEFAULT '',
`score` INT( 5 ) NOT NULL DEFAULT '0',
`round` INT( 5 ) NOT NULL DEFAULT '0',
`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
KEY(`id`)
);